### ISSUE TITLE
使用npm安装babel-node报错

### ISSUE THREAD

**Issue by zoujinbin** [gxchain/gxb-explorer#24]
![error1](https://user-images.githubusercontent.com/39855077/43814668-261c9c8e-9afe-11e8-8b1e-d9514e131dc2.jpg)

**Comment by lanhaoxiang** [comment]
npm install babel-cli -g

**Comment by zoujinbin** [comment]
根据提示使用命令“npm install -g babel-cli”安装babel-cli后，执行npm start后，报了一系列错误，如下图
![error2](https://user-images.githubusercontent.com/39855077/43814894-69fc660e-9aff-11e8-81d6-26b2eda25c9e.jpg)

**Comment by lanhaoxiang** [comment]
ENOSPC是系统对文件watch的限制(Not Enough Space)：
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
